## The following functions solve for and cache the inverse of any invertible matrix.
## A "matrix" x object is generated by makeCacheMatrix(). cacheSolve() can then solve
## for the inversion of x and cache the result. Thus, if cacheSolve() is called on the
## same "matrix" x, the cached object is retrieved, rather than re-computing the
## inverted matrix.

## Generates a "matrix" object x. This object is essentially a container for a matrix,
## providing additional properties. 
##     - set() sets the value of the CacheMatrix, based on the argument, invalidating
##       any previously cached value.
##     - get() returns the current value of the "matrix" object. 
##     - set_inverse() stores the current value of the inverse of the "matrix" object.
##     - get_inverse() returns the cached value of the inverse of the "matrix" object.
makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    set_inverse <- function(inverse) inv <<- inverse
    get_inverse <- function() inv
    list(set = set, get = get,
         set_inverse = set_inverse,
         get_inverse = get_inverse
    )
}

## Solves for or returns cached value of CacheMatrix x. It first tries to return a
## cached inverse value. If there is none, it retrieves the value of x and computes
## and returns the inverse, caching the inverse to be retreived later.
cacheSolve <- function(x, ...) {
    inv <- x$get_inverse()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$set_inverse(inv)
    inv
}
